name: Run Autograder
description: Reads a test report and runs the autograder

inputs:
  path:
    description: 'Optional path to the CTRF report file'
    required: false
    default: 'ctrf/ctrf-report.json'

runs:
  using: 'composite'
  steps:
    - name: Read CTRF report file
      id: read-report
      shell: bash
      run: |
        REPORT_PATH="${{ inputs.path }}"
        echo "content<<EOF" >> $GITHUB_OUTPUT
        cat "$REPORT_PATH" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Run autograder
      uses: brunchlabs/autograder@main
      with:
        studentId: ${{ github.actor_id }}
        organizationId: ${{ github.repository_owner }}
        repositoryName: ${{ github.event.repository.name }}
        report: ${{ steps.read-report.outputs.content }}
        branch: ${{ github.ref_name }}
