name: 'Autograder Action'
description: 'Automatically grades student submissions based on a report.'

inputs:
  context:
    description: 'The entire GitHub context'
    required: true
    type: string
  report:
    description: 'The serialized test report (in JSON format).'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: brunchlabs/autograder

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Write report to file
      shell: bash
      run: echo "${{ inputs.report }}" > report.json &&  printf '%s' '${{ toJson(github) }}' > context.json

    - name: Run autograder
      shell: bash
      run: node autograder.js
