on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      student:
        type: string
        required: true
      student_id:
        type: string
        required: true
      organization:
        type: string
        required: true
      organization_id:
        type: string
        required: true
      report:
        type: string
        required: true

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Repository: ${{ inputs.repo }}"
          echo "Student: ${{ inputs.student }}"
          echo "Student ID: ${{ inputs.student_id }}"
          echo "Organization: ${{ inputs.organization }}"
          echo "Organization ID: ${{ inputs.organization_id }}"
          echo "Report: ${{ inputs.report }}"
